Made several changes, all of them except the first below in the course of getting an ACL2(h) regression to succeed that was based on ANSI GCL.
Makefile:

  Improved Makefile by accumulating into OK_CERTS instead of into the
  "all" target, for example to avoid extra dependencies when
  ACL2_BOOK_CERTS or ACL2_BOOK_DIRS is defined.

  No longer try to avoid books/memoize/, which was already being built
  anyhow because of supporting xdoc/top.cert.

  Exclude models/y86/ for ACL2(h) regressions except for CCL, Allegro
  CL, and SBCL.  In an ANSI GCL ACL2(h) regression, I saw GCL hang for
  over 10 hours on each of four books under models/y86/
  (y86-basic/common/x86-state, y86-two-level/common/x86-state,
  y86-two-level-abs/common/x86-state-concrete, and
  y86-basic/py86/popcount), probably because of the demands of
  def-gl-thm.  But Allegro CL and SBCL took only a few minutes.  To
  support this change I modified cert_features.lsp to generate a value
  for ACL2_HOST_LISP; so we now can tell which host Lisp we're
  running.

centaur/aignet/from-hons-aig-fast.lisp:

  Added (comp t) to assist with ACL2(h) certification based on ANSI
  GCL, whch now works.

memoize/timer.lsp:

  Add acl2:: package prefix to most-positive-mfixnum.  CCL didn't have
  this problem because it's conditional on #-memoize-use-rdtsc.

memoize/tests.lisp

  Restricted the load of tests-raw.lsp to CCL, because success seemed
  to depend on the "magic" nature of numargs for CCL, and not just for
  tests marked in tests-raw.lsp with #+Clozure.  Without this change I
  got the following error using Allegro CL and ANSI GCL:

  Error:  the assertion (NOT (MEMOIZE::NUMARGS 'MEMOIZE::FROB)) failed.

centaur/gl/bfr-sat.lisp:

  Replaced ::hints by :hints in .  According to the Hyperspec
  (http://www.lispworks.com/documentation/HyperSpec/Body/02_ce.htm),
  such double-colon syntax does not necessarily indicate a keyword:

  ::aaaaa            undefined

  While this syntax was tolerated by CCL and probably some other
  Lisps, GCL seemed to interpret the package name as "" rather than as
  "KEYWORD".


git-svn-id: http://acl2-books.googlecode.com/svn/trunk@1750 303c5b2c-9740-0410-b014-fd8f9db7be32